<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= $block->escapeHtml(__('Toggle Nav')) ?></span></span>
<a class="logo" href="<?= $block->escapeUrl($block->getUrl('')) ?>">
    <img src="<?= $block->getViewFileUrl("/images/TG.png") ?>">
</a>
