<div>
    <div class="footer-container">
        <div class="footer-contact">
            <a href="https://magento.pruebaseo.com/contacto" class="footer-contactanos"> CONTÁCTANOS </a>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam nisi sed atque. </p>
            <div class="footer-ayuda">
                <img width="22" src="<?= $block->getViewFileUrl("/images/Minicart.svg") ?>">
                <span style="font-size: 17px;">¿Necesitas ayuda? ¡LLámanos!</span>
                <strong> (55) 2122 7100 </strong>
            </div>
            <div class="footer-redes">
                <img width="22" src="<?= $block->getViewFileUrl("/images/Minicart.svg") ?>">
                <img width="22" src="<?= $block->getViewFileUrl("/images/Minicart.svg") ?>">
                <img width="22" src="<?= $block->getViewFileUrl("/images/Minicart.svg") ?>">
                <img width="22" src="<?= $block->getViewFileUrl("/images/Minicart.svg") ?>">
            </div>
            <div class="footer-copyright">
                <span> Condiciones de uso | Aviso de privacidad </span>
                <span> Copyright C Tendencia Gastronomica derechos reservados </span>
            </div>
        </div>
        <div class="footer-enlaces">
            <div class="footer-grid">
                <div class="footer-navegacion">
                    <span class="footer-title"> Información </span>
                    <a href="#"> Enlace 1 </a>
                    <a href="#"> Enlace 2 </a>
                    <a href="#"> Enlace 3 </a>
                    <a href="#"> Enlace 4 </a>
                </div>
                <div class="footer-navegacion">
                    <span class="footer-title"> Logística </span>
                    <a href="#"> Enlace 1 </a>
                    <a href="#"> Enlace 2 </a>
                    <a href="#"> Enlace 3 </a>
                    <a href="#"> Enlace 4 </a>
                </div>
                <div class="footer-navegacion">
                    <span class="footer-title"> Newsletter </span>
                    <a href="#"> Enlace 1 </a>
                    <a href="#"> Enlace 2 </a>
                    <a href="#"> Enlace 3 </a>
                    <a href="#"> Enlace 4 </a>
                </div>
            </div>
        </div>
    </div>
</div>
