<div>
    <div class="footer-container">
        <div class="footer-contact">
            <a href="https://magento.pruebaseo.com/contacto" class="footer-contactanos"> CONTÁCTANOS </a>
            <p> ¿Tiene preguntas, comentarios o inquietudes sobre nuestras Tendencias? </p>
            <p>
                Horario de atención: de lunes a viernes de 9 a. A. M a  5 P.M. ET
            </p>
            <strong> Oficinas Corporativas </strong>
            <p> Av. 1° de Mayo 226 BIS, Col. San Andrés Atoto, Naucalpan, Edo.de México, C.P. 53500. </p>
            <div class="footer-ayuda">
                <img width="22" src="<?= $block->getViewFileUrl("/images/Phone.svg") ?>">
                <span style="font-size: 17px;">¿Necesitas ayuda? ¡LLámanos!</span>
                <strong> (55) 2122 7100 </strong>
            </div>
            <div class="footer-redes">
                <a href="https://www.facebook.com/TendenciaGastronomica/">
                    <img width="22" src="<?= $block->getViewFileUrl("/images/Facebook.svg") ?>">
                </a>
                <a href="https://www.instagram.com/tg_mexico/">
                    <img width="22" src="<?= $block->getViewFileUrl("/images/Instagram.svg") ?>">
                </a>
                <a href="https://www.linkedin.com/company/tendencia-gastronomica/">
                    <img width="22" src="<?= $block->getViewFileUrl("/images/LinkedIn.svg") ?>">
                </a>
                <a href="https://www.pinterest.com.mx/tendenciagastronmica">
                    <img width="22" src="<?= $block->getViewFileUrl("/images/Pinterest.svg") ?>">
                </a>
                <a href="https://www.youtube.com/channel/UC7f3RpocYRPeE-hvu3HmJ1A">
                    <img width="22" src="<?= $block->getViewFileUrl("/images/Youtube.svg") ?>">
                </a>
            </div>
            <div class="footer-copyright">
                <span> Condiciones de uso | Aviso de privacidad </span>
                <span> Copyright C Tendencia Gastronomica derechos reservados </span>
            </div>
        </div>
        <div class="footer-enlaces">
            <div class="footer-grid">
                <div class="footer-navegacion">
                    <span class="footer-title"> Sucursales </span>
                    <a href="#"> Naucalpan </a>
                    <a href="#"> Cancún </a>
                    <a href="#"> Vallarta </a>
                    <a href="#"> Cabos </a>
                </div>
                <div class="footer-navegacion">
                    <span class="footer-title"> Navegación </span>
                    <a href="/"> Home </a>
                    <a href="https://magento.pruebaseo.com/contacto"> Contacto </a>
                    <a href="#"> Nuevas Tendencias </a>
                </div>
                <div class="footer-navegacion">
                    <span class="footer-title"> Newsletter </span>
                    <p> Regístrate a nuestro Newsletter y obtén descuentos, promociones, cupones y mucho más. </p>
                    <a href="#"> Descargar </a>
                </div>
            </div>
        </div>
    </div>
</div>
