<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<li class="header-phone">
    <div style="display: flex; align-items: center;">
        <img width="22" src="<?= $block->getViewFileUrl("/images/Phone.svg") ?>" style="margin-right: 16px;">
        <a href="tel:5521227100"> (55) 2122 7100 </a>
    </div>
    <div style="display: flex; align-items: center;">
        <img width="22" src="<?= $block->getViewFileUrl("/images/Envelope.svg") ?>" style="margin-right: 16px;">
        <a href="mailto:ventas@t-g.com.mx"> ventas@t-g.com.mx </a>
    </div>
</li>
